import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import GoalProvider from "../context/GoalContext";
import { NextUIProvider } from "@nextui-org/react";
import BottomNav from "@/components/BottomNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// @ This is the root layout of the application
// @ It contains the Next UI Provider and Goal Provider
// @ It also contains the Bottom Navigation Bar

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <GoalProvider>
            <section className="relative bg-[#212121] min-h-screen">
              <div className="p-20 max-md:p-10  max-md:pt-14 max-md:px-1 max-sm:text-md">
                {children}
              </div>
              <div className="fixed bottom-0  left-0 right-0 md:hidden">
                <BottomNav />
              </div>
            </section>
          </GoalProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}
